[tool.poetry]
name = "nomad-challenge"
version = "0.1.0"
description = ""
authors = ["Kyle"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.1.2"
pillow = "^11.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
